name: Build and Deploy States JSON

on:
  schedule:
    # Runs at 06:00 UTC every Monday
    - cron: '0 6 * * 1'
  push:
    branches:
      - master  # Also trigger on push to master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Ensure this matches your project's required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install requests, add other necessary dependencies here

    - name: Run script to generate states.json
      run: |
        python fetch_and_process_data.py  

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        publish_dir: './'  # Specify the directory where states.json is output
        publish_branch: 'master'  # Specify the branch to push to, often gh-pages
        keep_files: false  # Keeps existing files at the deployment target
        commit_message: 'Deploy states.json'  # Commit message for the deployment

