name: Deploy States JSON to GitHub Pages

on:
  schedule:
    # Runs at 06:00 UTC every Monday
    - cron: '0 6 * * 1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Ensure the requests module is installed

    - name: Run script to generate states.json
      run: |
        python your_script.py  # Replace with the path to your Python script

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GP_TOKEN }}
        publish_dir: './'  # The directory where your states.json is output
        publish_branch: 'gh-pages'  # Branch to push to, replace with your target branch
        keep_files: false  # Set to true to not cleanup existing files in the branch
